/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorGrid: typeof import('./src/components/palette/ColorGrid.vue')['default']
    ColorItem: typeof import('./src/components/palette/ColorItem.vue')['default']
    InfoColumn: typeof import('./src/components/InfoColumn.vue')['default']
    LayoutBox: typeof import('./src/components/common/LayoutBox.vue')['default']
    OptionsPanel: typeof import('./src/components/OptionsPanel.vue')['default']
    TerminalWindow: typeof import('./src/components/tui/TerminalWindow.vue')['default']
  }
}
